sudo: required
language: ruby
rvm:
- 2.4.2
services:
- docker
install: true
before_script: docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
script: ./build.sh
env:
  matrix:
  - TEST_PLATFORM=debian-stretch
  - TEST_PLATFORM=centos-7
  global:
  - secure: dJoVPb0MhjI0TkBrjJURGwOArrORtVPmaCSEMBR9gr2uhDKahx9nBH3UyFvhCP2AX4RO8YWdlI6NitzuiX2z3lZAFdXvRRA/8jNgWooc5lYPQ8vW4+kxR+N3aUr4rzS4gOZH6yPEFunLOBqvxAr2u2LOqTqEOQIDmd3LSMtE37UiIXVjPSnIbXQfgHMG+qjmzKVDjWwJhNCtw38LM+LFEJY0EmQ2US+MRKzGv4+6B8cwBHvHJKnwJ5DLbo1pJL9Z6EeHMzdnpQRkM5y/lwukprwPo8YpapAIxDL7pwpWLuYsou8JztGSwD6zwlkkVemXkmFXb47x8et06DMcYpygcyfsoe8XE92IEwHzxJNJceHjJHm/F6U4+R9iHYa5LXXMEgEEF1AbumXK88Q7aHmA12SosnWhbW06wVAxDFbA74lnjE+Xcxl3BJWXeShxKaRRSKf+CGdPwiT3ExvgseJtk1VMcoZGUC0MsbBF3HTCCIFzyK6F5nbuDmipDXvcWtB/5ZLNg3+B0VsBrfItRnW7V5G5SLZQERdv1vkC/mgHobS4LFZ3bGjGjwQl1dQixUJMJYFXucMBjBRVVuLp0ppPiHXab8iwyCuCKy/YAUGXViSqnHMPRboGKFjiwdIsJOQsIleJwdv6LXvZI2TnHcYc58EGXfm2gtz0MahH/s3cop0=
  - secure: Pek0HTPp5gBw9llSLX6pQx697TxNMOYTOUrEGDAHP3Lq/bFUw4IxgsD7tkZ0Pyg4MLReiitIaCGcew5rJL7lKn7irD+GWMuYMDOHBtY2bLz5WL4n0UxfaA6/+BbYLB78bdXRv8viEcbZ5i4lQxFlLtNKQpN8jg2OigawIik4O/V61uQ1xMMU4LorBcBf7rWveCuFAA5Am8fRLdsLKyK03c3qPgI9lgFjZBILDlIizngvVgwBTsk3s9udk5ylizSKQYAD69JHgDduDI4P+QZF8surggN5fcaq8qXsGqlOuU81zi68Aayq+xFBdTpUO5mc4UKV6nw1qTlhiYwH5ReoChDbDpku9sPFh0++Zb/RGgxcGVjoIw4uYwfWgxmNXsb5hr8U72cQNINCibg8gi1woqHQnyhs3baDgoPl4oj9kQejN7oA0yClaZlt37ukfX1JXP8MWSkE8KvRZnZTdeEZcLhL1fnbImDvSgm8WXkj4ZhjIJKbdcf+7BR8K0YWD5qsltSuhh+UNP31Uq8CDv6+l++BZvPOBvY/+wU4Rf0uCN5xpmiI6qvw1rAW8+stJ5CvK9ZZKJFG6Yt63IssZR8gjsz1ljkPE4tlQWtLNkYWH1WGt7jngIZhRPs9tU1IgWzeLyThGND1+7+TlVDX4XmdU4pKX5Zx5L64I5GAtKvxcO8=
